config/routes.rb
Rails.application.routes.draw do
  get 'evaluations/create'

  get 'evaluations/destroy'

  get '/upload', to: 'images#new'
  post '/upload', to: 'images#create'

  get 'sessions/new'

  get 'top_pages/index'
  root 'top_pages#index'
  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :images
  resources :evaluations, only: %i[create destroy]
end

app/views/layouts/_header.html.haml
%body
  %header.navbar.navbar-default
    .container
      %nav
        %ul.nav.navbar-nav.navbar-left
          %li= link_to "Home", root_url
          - if logged_in?
            %li= link_to "Submit", upload_path
        %ul.nav.navbar-nav.navbar-right
          - if logged_in?
            - if current_user.admin?
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  Admin
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to "Users", users_path
                  %li= link_to "User Registration", signup_path
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                = current_user.name
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Profile", current_user
                %li= link_to "Settings", '#'
                %li.divider
                %li
                  = link_to "Log out", logout_path, method: "delete"
          - else
            %li= link_to "Sign up", signup_path
            %li= link_to "Log in", login_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title YamatoMurakamiHw
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    .content.center-block
      - flash.each do |message_type, message|
        %div{:class => "alert alert-#{message_type}"}= message
      = yield
      = debug(params) if Rails.env.development?